---
- name: Install Memcache, Start & enable SVC
  hosts: mcsrvgrp
  gather_facts: no
  tasks:
    - name: Install Memcache
      apt:
        name: memcached
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package

    - name: Start & Enable Memcache
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - svc

    - name: Enable remote login to memecache
      lineinfile:
        path: /etc/memcached.conf
        regexp: '^-l '   # it starts searching anything that start with -l
        line: '-l 0.0.0.0'   # and replace it with -l 0.0.0.0  then memcaches listens to
                              # all ip addresses not just local ip
        backup: yes
      notify:
        - Restart memcached
      tags:
        - conf

  handlers:
    - name: Restart memcached
      service:
        name: memcached
        state: restarted