- name: Build Artifact ROOT.war & SQL file to be copied in files/ directory
  import_playbook: build.yml # this playbook is going to create artifact localy on the control machine

- name: Set Hosts to Ip MApping in /etc/hosts file of all servers
  import_playbook: set_host_ip_map.yml # this playbook is going to update the ETC host file. it will use all the
                                        # ip that we mentioned them in hostsip file
- name: Setup dbserver
  import_playbook: db.yml # this playbook is going to install data base up and running

- name: Deploy SQL file on Dbserver
  import_playbook: dbdeploy.yml # this playbook is going to take our SQL file and
                                 #will run all the SQL queries from that so # this playbook will be pushed by
                                  # build.yml file.build.yml file will take the source code and build the artifact
                                  # at the same time and also push the SQL file so dbdeploy.yml can execute that
- name: Setup Memcached service
  import_playbook: memcache.yml  #is going to install, start and make sure Memchache is running on port 11211

- name: Setup rabbitmq service
  import_playbook: rabbitmq.yml # this installs all the rebbitmq dependencies, install rabbitmq, create rabbitmq user
                                # and password and some privilages

- name: Setup Tomcat application server
  import_playbook: appserver.yml # this is application server playbook and going to install and setup tomcat server
                                 # and also deploy the artifact. the artifact will build by build.yml file and already
                                 # push it from this playbook to application server in the tem directory
                                 # and this playbook is going to take the artifact from tem directory and deploy it to
                                 # tomcat home directory > this play book uses application.j2 template
- name: Setup Nginx webserver
  import_playbook: web.yml  # this playbook is going to provision Nginx service
                            # this playbook uses Nginxvpro.j2 template